version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # command: sh -c "yarn && yarn dev -p 8080"
    ports:
      - "8000:8000"
    image: next:latest
    networks:
      - koqzo_network
networks:
  koqzo_network:
    external: true
